### PR TITLE
Added Daemon-isation

### PR DESCRIPTION
**Pull request by mrwhale**

### CODE REVIEW

**Comment by perrin7** [comment]
Thanks so much for this, i promise ill test it and then merge it in the next few weeks.  Flat out with changing jobs and houses at the moment!

**Comment by perrin7** [comment]
I'm actually not sure this is necessary now, @carlossg has created an upstart config file, which allows it to run as a service without additional code in the python script.  
I think this is a better solution, any comments? (@mrwhale)

**Comment by mrwhale** [comment]
Sounds good to me! probably a better way anyway. I just hacked this together so I could have it running in the background without using screen. Nice work @carlossg!

**Comment by perrin7** [comment]
Awesome.  Closed.

**Pull request closed without merging**
